Naming convention for Vulkan
Maksasj/bebone pull request #98
Opened 2024-06-25 13:46 UTC by Maksasj

Closing #97

2024-06-27 17:39 UTC, Soskar1 requested changes
Fix everything

2024-06-27 17:39 UTC, Soskar1 commented on src/bebone/gfx/vulkan/vulkan_pipeline_manager.h
> +                const std::shared_ptr<VulkanSwapChain>& swapChain,
swapChain -> swap_chain

2024-06-27 17:39 UTC, Soskar1 commented on src/bebone/gfx/vulkan/vulkan_pipeline_manager.h
>                  const std::vector<VulkanConstRange>& constantRanges,
constantRanges -> constant_ranges

2024-06-27 17:40 UTC, Soskar1 commented
[bufferInfo -> buffer_info](https://github.com/Maksasj/bebone/blob/97-naming-convention-for-vulkan/src/bebone/gfx/vulkan/vulkan_buffer.h#L53)

2024-06-27 17:40 UTC, Soskar1 commented
[const std::vector<std::shared_ptr<VulkanDescriptorSet>> & descriptors -> const std::vector<std::shared_ptr<VulkanDescriptorSet>>& descriptors](https://github.com/Maksasj/bebone/blob/ca97250b5c76d21a89b021381ffc38bb15d98fa7/src/bebone/gfx/vulkan/vulkan_pipeline_tuples.cpp#L12)

2024-06-27 17:41 UTC, Soskar1 commented
[VulkanDevice &device -> VulkanDevice& device](https://github.com/Maksasj/bebone/blob/ca97250b5c76d21a89b021381ffc38bb15d98fa7/src/bebone/gfx/vulkan/vulkan_pipeline_tuples.cpp#L55)

2024-06-27 17:42 UTC, Soskar1 commented
[const std::vector<std::shared_ptr<VulkanDescriptorSet>> & descriptors -> const std::vector<std::shared_ptr<VulkanDescriptorSet>>& descriptors](https://github.com/Maksasj/bebone/blob/ca97250b5c76d21a89b021381ffc38bb15d98fa7/src/bebone/gfx/vulkan/vulkan_pipeline_tuples.h#L31)

2024-06-27 17:43 UTC, Soskar1 commented
[VulkanDevice &device -> VulkanDevice& device](https://github.com/Maksasj/bebone/blob/ca97250b5c76d21a89b021381ffc38bb15d98fa7/src/bebone/gfx/vulkan/vulkan_pipeline_tuples.h#L43)

2024-06-27 18:28 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_buffer.cpp
> +        VkBufferCreateInfo create_Info{};
ok my lord

2024-06-27 18:28 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_descriptor_set_layout.cpp
> +        extendedInfo.bindingCount = binding_flags.size();
sure my lord

2024-06-27 18:29 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_instance.cpp
>          VkApplicationInfo appInfo = {};
please blame me more 🥵

2024-06-27 18:29 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_instance.cpp
>          createInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
ok

2024-06-27 18:30 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_instance.cpp
>              VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo;
ok sir

2024-06-27 18:31 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_instance.cpp
> +            for (const auto &layerProperties : availableLayers) {
ok

2024-06-27 18:33 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_device.cpp
> +    uint32_t VulkanDevice::find_memory_type(uint32_t type_filter, VkMemoryPropertyFlags m_properties) {
intended, stands for **memory properties**, but ok, will change to mem_properties

2024-06-27 18:34 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_pipeline_manager.h
> +                const std::shared_ptr<VulkanSwapChain>& swapChain,
ok

2024-06-27 18:34 UTC, Maksasj commented on src/bebone/gfx/vulkan/vulkan_pipeline_manager.h
>                  const std::vector<VulkanConstRange>& constantRanges,
ok

2024-06-28 06:58 UTC, Soskar1 approved these changes

2024-06-28 11:30 UTC, merged